#################################################################################################################
#                                                                                                               #
#             ███╗░░░███╗░█████╗░███╗░░██╗░█████╗░██╗░░░░░███████╗██╗░░░██╗███████╗██╗░░░░░░██████╗             #
#             ████╗░████║██╔══██╗████╗░██║██╔══██╗██║░░░░░██╔════╝██║░░░██║██╔════╝██║░░░░░██╔════╝             #
#             ██╔████╔██║██║░░██║██╔██╗██║██║░░██║██║░░░░░█████╗░░╚██╗░██╔╝█████╗░░██║░░░░░╚█████╗░             #
#             ██║╚██╔╝██║██║░░██║██║╚████║██║░░██║██║░░░░░██╔══╝░░░╚████╔╝░██╔══╝░░██║░░░░░░╚═══██╗             #
#             ██║░╚═╝░██║╚█████╔╝██║░╚███║╚█████╔╝███████╗███████╗░░╚██╔╝░░███████╗███████╗██████╔╝             #
#             ╚═╝░░░░░╚═╝░╚════╝░╚═╝░░╚══╝░╚════╝░╚══════╝╚══════╝░░░╚═╝░░░╚══════╝╚══════╝╚═════╝░             #
#                                                                                                               #
#################################################################################################################

messages:
  earn_xp: '&6[MonoLevels] &7You are earned &a+%earned%XP &7from &a%entity%'
  levelup:
    - '&6&m--------------&6[ &aLevel Up &6]&m--------------'
    - '&aNew Level &8: &7%new%'
    - '%progress%'
    - '&7WoW! You are level upped!'
    - '&6&m--------------&6[ &aLevel Up &6]&m--------------'

mobs:
  ZOMBIE:
    xp_amount: 200
    xp_limit: 1000